FROM maven:3.8.3-openjdk-17 as build
WORKDIR /workspace/app
COPY src ./src
COPY pom.xml ./
ARG DB_HOST_ARG
ARG DB_NAME_ARG
ARG DB_PASSWORD_ARG
ARG DB_USERNAME_ARG
ENV DB_HOST=$DB_HOST_ARG
ENV DB_NAME=$DB_NAME_ARG
ENV DB_USERNAME=$DB_USERNAME_ARG
ENV DB_PASSWORD=$DB_PASSWORD_ARG
RUN mvn clean install

FROM eclipse-temurin:17-jdk-alpine
ARG DB_HOST_ARG
ARG DB_NAME_ARG
ARG DB_PASSWORD_ARG
ARG DB_USERNAME_ARG
ENV DB_HOST=$DB_HOST_ARG
ENV DB_NAME=$DB_NAME_ARG
ENV DB_USERNAME=$DB_USERNAME_ARG
ENV DB_PASSWORD=$DB_PASSWORD_ARG
COPY --from=build workspace/app/target/poll-rest-api.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]