name: Deploy Polls-Rest-API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build and push image
      env:
        DB_HOST: ${{ secrets.GIT_DB_HOST }}
        DB_NAME: ${{ secrets.GIT_DB_NAME }}
        DB_USERNAME: ${{ secrets.GIT_DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.GIT_DB_PASSWORD }}
      run: |
        docker build -t julio16j/poll-rest-api:latest --build-arg DB_HOST_ARG=$DB_HOST --build-arg DB_NAME_ARG=$DB_NAME --build-arg DB_USERNAME_ARG=$DB_USERNAME --build-arg DB_PASSWORD_ARG=$DB_PASSWORD .
        docker push julio16j/poll-rest-api:latest
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'Poll-Rest-API'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'docker.io/julio16j/poll-rest-api:latest'
